#! /bin/sh
#ObliviousGmn, May 2020

. "$HOME/.cache/wal/colors.sh"

# Start Ups ..
killall -p polybar
polybar simple &
sxhkd &
compton -c -t-5 -l-5 -r3 -o.50 &
(wal -q -R &)
(pywalfox deamon &)

# Workstations ..
bspc monitor -d 1 2 3 4

# Configs ..
bspc config border_width         2
bspc config window_gap           33
bspc config split_ratio          0.53
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding			 33
bspc config focus_follows_pointer true

# Colors ..
bspc config normal_border_color $background
bspc config focused_border_color $color1

# Windows Rules .. 

# Terminal Station ..
bspc rule -a URxvt desktop='^1' follow=on

# GTK Station ..
# bspc rule -a Gcolor2 desktop='^2' follow=on
bspc rule -a Xfd desktop='^2' follow=on

# Web Station ..
bspc rule -a Google-chrome desktop='^3' follow=on
bspc rule -a firefox desktop='^3' follow=on

# Image Station .. 
bspc rule -a feh desktop='^4' state=tiled follow=on

