#!/bin/sh
# ObliviousGmn, May 2020
# Movement
# Wmutils Window Managing
######################### 

wid=$(pfw)
w=$(wattr w $wid)
h=$(wattr h $wid)

fh=$(wattr h `lsw -r`)
fw=$(wattr w `lsw -r`)

Left=" 10 "
Top=" 42 "
Bottom=$(( $fh - $h - 12 ))
Right=$(( $fw - $w - 12 ))
CenterX=$(( $fw / 2 - $w / 2 ))
CenterY=$(( $fh / 2 - $h / 2 ))

Top_Left(){
	wtp $Left $Top $(wattr whi $wid)
}

Top_Right(){
	wtp $Right $Top $(wattr whi $wid)
}

Top_Center(){
	wtp $CenterX $Top $(wattr whi $wid) 
}


Bottom_Left(){
	wtp $Left $Bottom $(wattr whi $wid) 
}

Bottom_Right(){
	wtp $Right $Bottom $(wattr whi $wid) 
}

Bottom_Center(){
	wtp $CenterX $Bottom $(wattr whi $wid)
}

Center(){
	wtp $CenterX $CenterY $(wattr whi $wid)  
}

Center_Right(){
	wtp $Right $CenterY $(wattr whi $wid)
}

Center_Left(){
	wtp $Left $CenterY $(wattr whi $wid)
}


case $1 in
	tl) Top_Left ;;
	tr) Top_Right ;;
	tc) Top_Center ;;

	bl) Bottom_Left ;;
	br) Bottom_Right ;;
	bc) Bottom_Center ;;

	cr) Center_Right ;;
	cl) Center_Left ;;
	c)  Center ;;
esac

