#!/bin/sh

# ObliviousGmn, April 2015
# https://github.com/ObliviousGmn
# Screenshot popup 

. $HOME/Gmnbox/Panel/bar_config

# Fancy pop for screenshot .. 
aplay -q $HOME/Gmnbox/Sounds/camera.wav &
scrot -d 1 -z -t 15 -q 100 '/home/doku/Wallpaper/Screens/%m_%d_%Y.png'

